### ISSUE TITLE
Update the Boilerplate

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-boilerplate-vue#1]
The boilerplate needs some love:

- [x] Update the SDK to the latest release (currently `v8.2.1`)
- [x] Make sure that the boilerplate still connects & works with
    - [x] Superhero Wallet
- [x] Update all other dependencies to the newest version
- [x] Switch CI to Github Actions

**Comment by the-icarus** [comment]
@marc0olo I would like to take care of this one

**Comment by marc0olo** [comment]
> @marc0olo I would like to take care of this one

Nice - can you give an estimate about the target date to finish this? @kenodressel can you confirm that I can assign to @the-icarus when he provided a target date?

**Comment by marc0olo** [comment]
Btw I updated the requirements. It's only required to make sure somebody can connect with their Superhero Wallet. Connection to base aepp is no hard requirement anymore.

**Comment by the-icarus** [comment]
@marc0olo I would expect it to be done no later than October, 3rd. There is a high chance to complete it earlier but I can't promise.

**Comment by marc0olo** [comment]
> @marc0olo I would expect it to be done no later than October, 3rd. There is a high chance to complete it earlier but I can't promise.

you are ready to go, issue is assigned to you :-)

**Comment by marc0olo** [comment]
thanks for your contribution @the-icarus, you can now provide your AE address and fill in the form as described in the README of the bounties repository ;-)

**Comment by ErkanKanden** [comment]
@the-icarus here is your bounty reward :)
https://explorer.aeternity.io/transactions/th_YEniqtXqbB4iwJZDaUmpn3fpsiXqvRKeaLe7ejwgFfQyhmoNt
