### ISSUE TITLE
network id doesn't update when switching network

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-boilerplate-vue#6]

**Comment by marc0olo** [comment]
@janmichek not sure if we should fix this if the intention is that the aepp in general only allows 1 network where we provide respective error handling if user has configured the wrong network in their wallet

I think we can close this and you just focus on #10 

what's your opinion?

**Comment by janmichek** [comment]
> @janmichek not sure if we should fix this if the intention is that the aepp in general only allows 1 network where we provide respective error handling if user has configured the wrong network in their wallet
> 
> I think we can close this and you just focus on #10
> 
> what's your opinion?

This needs to be solved first. In order to recognize 'wrong' network, first I need to know to which I am connected which si buggy

**Comment by marc0olo** [comment]
got it!

we really need to sort this out. it's pain in the ass for devs outside that don't even know about how to deal with the wallet connection in general. is it (still) a bug in the SDK? keep me updated :)
