### ISSUE TITLE
Upgrade to sdk v12

### ISSUE THREAD

**Issue by janmichek** [aeternity/aepp-boilerplate-vue#9]
I think we will want to have the boilerplate up-to-date with the current SDK version

please upgrade dependencies and accommodate breaking changes when it will be released

https://github.com/aeternity/aepp-sdk-js/issues/1535

**Comment by marc0olo** [comment]
Hi @janmichek,

can you tackle this please? as already mentioned in a previous PR (can be ignored and will be closed) there is also some stuff to be fixed in regards to the README when I remember correctly:
- https://github.com/aeternity/aepp-boilerplate-vue/pull/7
